### ISSUE TITLE
百度汉语本身的bug

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#10]
对https://github.com/sth2018/FastWordQuery/issues/9 的补充。

刚才测试的过程中有发现了百度汉语本身也有bug。

比如查找“一旦”、“女弟”这两个词，百度汉语会自动跳转至“亘”、“娣”的字条，把它当成偏旁查找了。

https://hanyu.baidu.com/s?wd=%E4%B8%80%E6%97%A6  （一旦→亘）
https://hanyu.baidu.com/s?wd=%E5%A5%B3%E5%BC%9F  （女弟→娣）

但是百度词典却没有这个问题，内容也几乎一样：

http://dict.baidu.com/s?wd=%E4%B8%80%E6%97%A6&ptype=word#detailmean （一旦）
http://dict.baidu.com/s?wd=%E4%BA%98&ptype=word#detailmean （亘）

http://dict.baidu.com/s?wd=%E5%A5%B3%E5%BC%9F#detailmean （女弟）
http://dict.baidu.com/s?wd=%E5%A8%A3#detailmean （娣）

**Comment by sth2018** [comment]
这应该不算是BUG，而是因为汉语中本来也没有这个词吧
