### ISSUE TITLE
百度词典四字成语好像查不到+缩进

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#11]
继续测试百度词典，发现 踽踽独行、城下之盟 查不到详细释义：

http://dict.baidu.com/s?wd=%E8%B8%BD%E8%B8%BD%E7%8B%AC%E8%A1%8C#detailmean
http://dict.baidu.com/s?wd=%E5%9F%8E%E4%B8%8B%E4%B9%8B%E7%9B%9F#detailmean

但是酒帘、龙蛇、鼍……等大多数词都能查到。

推测可能是四字成语的网页格式和其他的不太一样？

还有一个小问题，详细解释查到后文字左侧有一块缩进，这个不知道能否去除。

谢谢。

**Comment by sth2018** [comment]
缩进是为了保持百度原有排版导致的，如果破坏他原有的排版，可能会不好看，特别是详细解释，这个我有试过了。

**Comment by sth2018** [comment]
如果你想要去除左则空白，  建议你修改卡片正反面样式里设置自己满意的样式来解决，希望能帮到你。
