### ISSUE TITLE
增加有道韩语

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#12]
默认的已经有了有道英语、法语，请求抽空增加有道韩语。

http://dict.youdao.com/w/ko/%EA%B0%88%EB%B9%84%EC%B0%9C/
http://dict.youdao.com/w/ko/%E7%82%96%E6%8E%92%E9%AA%A8/

**Comment by sth2018** [comment]
有时间的时候会处理的

**Comment by Steven630** [comment]
谢谢，期待！
