### ISSUE TITLE
希望能添加，词根词缀，词源的字典。

### ISSUE THREAD

**Issue by Ryanshuai** [sth2018/FastWordQuery#127]
我也是程序员，可以参与开发。爬数据啥的。

**Comment by Loiks** [comment]
https://github.com/wangzilinn/Anki-assistant

你可以把这个修改成query支持的文件吗...

**Comment by Ryanshuai** [comment]
hi，
我从三个词根词缀网站，多个词根词缀字典。爬出来了到GRE单词级别的单词的词根词缀。
仓库里还有其他的，助记方法，十张单词图片，不同前缀单词对比，不同后缀单词对比， 相似(单词距离)单词对比。
https://github.com/Ryanshuai/make_anki_word_list/tree/master/output

**Comment by Loiks** [comment]
啊啊啊 谢谢 原来在优词上面中文词根词源都是童哥说单词的里面的内容...我去找了个童哥说单词的词典文件就好了

再次感谢 哈哈
