### ISSUE TITLE
保存预设选项

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#13]
既有英语卡片，也有中文卡片，经常需要切换词典选择。

要是能让用户保存几个预设选项就好了。

比如查中文，filed1是中文词典、field2是百度汉语，card type是Chinese。查英文field1、2、3是三本不同的英文词典，card type是English。

这样查不同的卡片只要选择预设的选项，可以省去一一修改词典、卡片选项的麻烦。

这个功能实现起来可能比较麻烦，不过确实实用。

**Comment by sth2018** [comment]
目前就是这样子的，你查询的时候使用的就是你预设的卡片类型，每个卡片类型的设置都会有保存的，只是之前的版本在设置时不会自动载入，这个问题在我前面的提交修改中已经改过了，你可以更新到最新代码试一下。

**Comment by Steven630** [comment]
哦，明白了。因为我很多卡片用的是同一个卡片类型，所以才需要不停修改。

**Comment by sth2018** [comment]
建议你按照你希望查询的词典来源添加不同的卡片类型

**Comment by Steven630** [comment]
好的，谢谢！

**Comment by Steven630** [comment]
有一个增加快捷键和预设选项的想法。

绝大部分卡片一次查询就可以了，所以每个卡片类型保存设置一般够用。不过实际上也有不少卡片需要单独查。

比如几天前刚增加的查询图片功能。可能只有部分卡片需要。如果原来的卡片除了front外有三个field；词典一、词典二、其他。大部分卡片查询词典一、词典二，有些卡片需要在‘‘其他’’添加Bing图片。

按照现在的设置，就得ignore词典一、词典二，再到‘其他’选择查询图片。查完那几个之后，以后又要重新设置。

能否将设置和快捷键相连，比如ctrl+Q就是当前卡片类型的默认查询，ctrl+I是在其他栏查询图片，等等。

界面的话，就是在原来界面上添加‘为当前设置添加快捷键’的选项。

这样一来，大部分的卡片CTRL+Q，碰到某几张要图片了，直接CTRL+I，也不用反复改设置。

平时我还会遇到词组查询的问题。比如let sth. slide这个词组，词典一需要查let something slide，词典二需要查let sth. slide，否则就查询不到。现在为了两个词典的内容都查询到，我先将front的改成let something slide，ignore词典二，查完词典一，再改成let sth. slide，ignore词典一，查词典二。这样也需要反复更改设置。

如果能自定义CTRL+1是只查询词典一，CTRL+2是只查询词典二，再碰到这种情况就方便多了（ 不过还是需要修改一次front）。

**Comment by sth2018** [comment]
添加了一个支持多配置的特性，你可以试用一下
![options](https://user-images.githubusercontent.com/40681172/43896438-5e342264-9c0b-11e8-9224-c04c6bba397e.png)

**Comment by Steven630** [comment]
非常感谢，辛苦啦

另外，是否考虑在ignore、skip non-empty上方增加全选、全不选的勾选框。
