### ISSUE TITLE
忽略声调符号

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#15]
比如查risqué，有的词典得查risque。FWQ在查询时有办法忽略声调吗？

类似于这个插件的功能：
https://ankiweb.net/shared/info/1924690148

**Comment by sth2018** [comment]
只针对汉语？

**Comment by sth2018** [comment]
在设置里面添加了一项忽略声调的设置，勾上就会有你要的效果

**Comment by Steven630** [comment]
主要是英语中外来词（多数是法语），像是risqué、à la carte、déjà vu等。有很多词典词条就是risque、a la carte、deja vu，如果查询有声调的字母，可能查不到。

汉语反而用不上，因为不太会有人把拼音当作查询目标吧。

**Comment by sth2018** [comment]
这项设置是针对所有词典的，勾上就会实现你所说的效果

**Comment by Steven630** [comment]
谢谢，辛苦啦

**Comment by sth2018** [comment]
不客气，你自己下源码更新试一下吧
