### ISSUE TITLE
词典互补

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#16]
又想到一个功能，不知道能否实现互补查询的功能，即让用户为每个field都设置两本（甚至多本）词典，按优先级排列，词典A查不到则查词典B，B查不到则查C；如果一开始A查到了则不再查B、C。

现在的界面是

Field1  词典选择
Field2  词典选择
Field3  词典选择
...

如果实现词典互补后则可变成

Field1  词典A选择  词典B选择 
Field2  词典A选择  词典B选择 
Field3  词典A选择  词典B选择 
...

举例的话，词典A为本地词典，如果本地查不到，则查词典B（如Bing、有道）。要是一开始本地查到了，就不继续查B了。当然用户也可以每个filed都只选一本词典，那就和现在的功能一样。

不知道实现这个功能是否复杂。有一个叫[AnKindle](https://ankiweb.net/shared/info/1016931132)的Anki插件，是配合Kindle生词本用的，可以互补查询，但不能像FWQ这样同时查询多本词典。要是两个功能结合起来就好了。

如果上述功能实现起来太麻烦，是否可以考虑“条件查询”功能。

比如100个单词的某个field都查了本地词典，有7个单词没查到，需要用网络词典补充。能否设置让FWQ先判断那个field是否为空，如果是，再继续查询网络。最后的结果是93个来自本地词典，剩下的7个用的网络词典。实际上结果和“互补查询”一样。

以上思路供高手参考，谢谢！

**Comment by sth2018** [comment]
功能实现不麻烦，但设置界面会变得非常复杂。

我现在实现你这个需求的方式是先设置好字典，全选查询，然后在浏览器窗口里搜索某字段值为空的项，然后再全选再查，直到补全。

对于设置界面你有什么想法，如果能让设置又简单又能实现上面的需求的话，确实是一个不错的功能。

**Comment by sth2018** [comment]
嗯，下面这个想法非常不错，我尽快加上这个功能

**Comment by Steven630** [comment]
谢谢！

还有一个想法，就是现在的ignore this field是下拉选项的一部分，和词典混杂在一起。其实也可以做成勾选，如果勾选了，则“词典选择”、“仅更新空白区域”自动变为灰色不可编辑，这样更方便。

忽略 囗 Field1 词典选择 仅更新空白区域 囗 
忽略 囗 Field2 词典选择 仅更新空白区域 囗
忽略 囗 Field3 词典选择 仅更新空白区域 囗

**Comment by sth2018** [comment]
这样禁用跟开启的话会比较方便些
