### ISSUE TITLE
可以将某本词典所有的词条都一一做成卡片吗？

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#17]
不好意思，又来打扰。

有些短小的词典，想请教有什么方法能将一本词典所有词条都批量转换成卡片（一个field是词头，另一个是释义），而不必根据现有field查询？

谢谢。

**Comment by sth2018** [comment]
Anki的导入功能就能实现

**Comment by Steven630** [comment]
谢谢！将mdx转换为txt有什么工具推荐吗？

**Comment by sth2018** [comment]
你首先要准备一份单词表，把整本mdx转换成文本，这量有点大，你是想拿整本词典来背单词？这太夸张了😣

**Comment by Steven630** [comment]
有网友自制的词典，比如用法词典等等，也就几百或者几千词，所以还不算太大

**Comment by Steven630** [comment]
好像有个getdict.exe还不错
