### ISSUE TITLE
有“-”单词的查询

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#18]
比如 jet-black这个词，有的词典可以查到，有的则必须查jet black（“-”换成空格）。
有没有可能和忽略声调类似，增加一个选项，如果英文单词有“-”，先查有“-”的原型（jet-black），如果查不到，则将“-”替换为空格（jet black）再查一次？

谢谢。

**Comment by sth2018** [comment]
普通的词典对这类的词的查询都不是非常的友好，如果找不到尝试另外的方式会影响查询速度，因为很多词他不是完全查不到，而是有部分字段查询不到。
有没有那种对词组和你举例这类合成词支持比较好的词典，如果有的话我可以专门有针对性的写一个字典服务来解决这个问题

**Comment by sth2018** [comment]
插件里面解析html的时候效率特别低，所以你在查询像bing这样的词典的时候速度就明显比bing_xtk或百词斩慢很多，因为bing_xtk跟百词斩查询结果是json格式，解析效率非常高。

**Comment by Steven630** [comment]
我现在用的也都是一般的词典，好像也没特别全的，不过这是个小问题，要是影响速度的话就算啦。

怎么样判断是否为json格式呢？

**Comment by sth2018** [comment]
返回的值看一眼就知道是什么格式了，对应的字典都是针对返回的内容做分析，然后提取各字段的值，所以很多字典没特别针对性的做的话，就只有一个Default字段。

**Comment by Steven630** [comment]
现在内置朗文词典的解析主要是为了提取音频吧？

说句题外话，刚发现一个不错的在线词典，Cambridge Advanced Learner’s Dictionary, 4th Edition

比如查ask：
https://dictionary.cambridge.org/dictionary/english/ask

查询结果实际上有三个词典（另两个是美语词典、商务词典），但还是第一个CALD4最权威

只要需要保留div class = pos-header、div class= pos-body
后面的Grammar、Idiom(s)、Phrasal verb(s)需要再点连接，所以没有太大的意义。

要是觉得可以，不妨也加入内置的。感觉CALD的解释比牛津的更清楚。

div class =smartt也不需要，如：https://dictionary.cambridge.org/dictionary/english/hospital-ball

**Comment by sth2018** [comment]
好，我找时间加上

**Comment by Steven630** [comment]
谢谢。

精益求精，令人敬佩！👍
