### ISSUE TITLE
请教CSS的问题

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#19]
某本词典只有mdx、mdd文件，解压mdd文件得到了css文件并加以修改，另存为同名文件。
该css文件放到原词典文件夹，现在有mdx、mdd、css三个文件。

用Mdict查询，已经能看见修改的效果，但是FWQ查询后仍然是原来的效果。

请问css文件的文件名需要和mdx一样吗？还是说就保留mdd解析出来的css文件名就可以？

谢谢。

**Comment by sth2018** [comment]
查询的时候有没有提示选择css文件？

**Comment by sth2018** [comment]
麻烦你把词典共享一下给我，方便我查问题。
现在在外地，要过些天才能修bug了😁
碰到问题你先在这里留言吧

**Comment by Steven630** [comment]
没有提示。我修改css前就已经用FWQ查询过了，是不是需要重新删除添加一下？

**Comment by sth2018** [comment]
是不是勾选了略过有值项了？

**Comment by Steven630** [comment]
没有选。我刚才忍不住把mdx.db、mdd.db给删了，现在又出现类似上次的错误了……
正在折腾

**Comment by Steven630** [comment]
还好，现在这个问题没了。但是css样式还是不变。应该是我操作的问题

**Comment by Steven630** [comment]
我再试试，要是还不行就分享词典。

麻烦请教，现在文件夹有
a.mdx （a是词典的名字，下同）
a.mdd（这个mdd里本身自带css，文件名姑且叫做b.css）
b.css（这是我修改的css，只修改了字体，文件名保留了b，而不是mdx的a）

如果这样的话，理论上FWQ会调用修改后的css吗？
还是说我得把mdd重新打包？

**Comment by sth2018** [comment]
需要打包mdd，而且css还是会使用原来的文件名的

**Comment by sth2018** [comment]
这个css文件名跟字典mdx文件名无关，而是根据查询到的内容有关

**Comment by Steven630** [comment]
用MdxBuilder打包吗？好多选项不会……
有没有办法让FWQ忽略mdd内置的css，而调用文件夹里修改后的css呢？

**Comment by sth2018** [comment]
如果mdd文件不存在，就会调用文件夹里的css的

**Comment by Steven630** [comment]
mdd文件包含一些图片，如果删除那些图片就显示不了了。

要是能像Mdict，外置css优先级大于mdd内置的css就好啦。

还是怪我技术不行，不会打包……

**Comment by Steven630** [comment]
谢谢大神！
