### ISSUE TITLE
增加Yahoo字典

### ISSUE THREAD

**Issue by jjchen8888** [sth2018/FastWordQuery#23]
可以增加Yahoo字典嗎?
https://tw.dictionary.yahoo.com/

**Comment by sth2018** [comment]
可以

**Comment by jjchen8888** [comment]
希望可以有這幾個欄位。
1. 音標
2. 發音
3. 詞性及中文解釋
4. 所以得釋義在同一個欄位

謝謝你

**Comment by sth2018** [comment]
你好，已经添加好了！

**Comment by jjchen8888** [comment]
Dear Sir,
謝謝你 Best Regards 

    sthoo <notifications@github.com> 於 2018/7/27 (週五) 9:52 AM 寫道﹕
 

 你好，已经添加好了！—

**Comment by jjchen8888** [comment]
Dear Sir,
附件這一張圖片是我所用Yahoo-Dict所下載的單字發音。我輸入test, 但單字的發音檔案後面出現一些亂碼，是否可以將程式修正為單字本身?例如:yahoo_dict-test.mp3, Yahoo_dict_book.mp3....等等 Best Regards 

    JJ chen <jjchen8888@yahoo.com.tw> 於 2018/7/27 (週五) 5:38 PM 寫道﹕
 

 Dear Sir,
謝謝你 Best Regards 

    sthoo <notifications@github.com> 於 2018/7/27 (週五) 9:52 AM 寫道﹕
 

 你好，已经添加好了！—
