### ISSUE TITLE
MarginNote 导出的 Anki 词条，查询后无法写入字段

### ISSUE THREAD

**Issue by hmgqzx** [sth2018/FastWordQuery#26]
**Describe the bug**
从 [MarginNote](https://marginnote.com/?lang=zh-hans) 里导出的 Anki 词条，查询成功，但无法写入对应字段

**To Reproduce**
[测试样本（sample.apkg）](https://github.com/hmgqzx/myImageHosting/blob/master/chemistry/sample.apkg?raw=true)

**Screenshots**
![](https://github.com/hmgqzx/myImageHosting/blob/master/chemistry/2018-07-31%20at%20%E4%B8%8A%E5%8D%8812.23.png?raw=true)
![](https://github.com/hmgqzx/myImageHosting/blob/master/chemistry/2018-07-31%20at%20%E4%B8%8A%E5%8D%8812.24.png?raw=true)

编辑单词字段，问题仍旧，很疑惑。

![](https://github.com/hmgqzx/myImageHosting/blob/master/chemistry/2018-07-31%20at%20%E4%B8%8A%E5%8D%8812.45.png?raw=true)

**Desktop**
 - OS: OS X
 - Version 10.12

**Additional context**

**Comment by sth2018** [comment]
引起查询不到的原因是导出的单词字段实际的内容是：<div class="mbooks-question">obscure</div>

**Comment by sth2018** [comment]
添加了一个新的特性，查询时自动过滤掉单词中的html标签，解决你碰到的这个问题。

**Comment by hmgqzx** [comment]
感谢作者这么快修复~ 不过好像只是在在线查询里才过滤，本地内置词典仍不行？
