### ISSUE TITLE
每次打开anki都提示更新，已经下好覆盖了

### ISSUE THREAD

**Issue by wyx1818** [sth2018/FastWordQuery#28]
总是弹出update界面，点更新没有反应，就在github下载了手动更新，还是这样。
anki版本，2.1.0rc2

**Comment by sth2018** [comment]
设置里面有个自动检测更新的选项的，如果你不想自动更新可以关掉它，更新没反应有可能是国内网络被墙，访问不稳定导致的。

**Comment by sth2018** [comment]
测试过多次，是因为国内网络访问github不稳定所致。你可以在Setting界面里把自动检测更新选项关闭。
