### ISSUE TITLE
查图片

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#29]
可以支持查图片吗？这对有些名词有直观的帮助。

比如azalea（映山红），

可以查http://cn.bing.com/images/search?q=azalea
然后默认将第一张图片加至相应field。

谢谢。

**Comment by sth2018** [comment]
百词斩有查图片字段功能

**Comment by Steven630** [comment]
刚才试了试，毕竟词汇量还是小了点，比如azalea就查不到。

最常见的事物反而不需要图片辅助，比如电视机、电脑，就算没有图片大家也都知道什么样。但是某些植物、动物、装置就不是这样了，要知道究竟是什么，非得搜索引擎不可。

**Comment by sth2018** [comment]
我试试看行不行

**Comment by Steven630** [comment]
谢谢。例子用的bing是因为百度对外文搜索支持得不够好，谷歌又上不了，或许还会有更好的搜图网站。

**Comment by sth2018** [comment]
查询不了，以这个网址做为查询地址的话，会出现很多的异常错误

**Comment by sth2018** [comment]
刚开始测试不行，后来找到了问题所在解决了，已经添加了图片查找，确实不错，比百词斩的图片来得更全面。

**Comment by Steven630** [comment]
谢谢！！
