### ISSUE TITLE
大小写敏感问题

### ISSUE THREAD

**Issue by Sapph1reX** [sth2018/FastWordQuery#30]
作者您好，我发现现在的版本查询时是大小写敏感的，例如stoic这个词，在Shorter Oxford English Dictionary里面词条是Stoic，所以就查不出来。因为我要同时查询两部词典，所以希望查询时能忽略大小写问题。现在的顾虑就是忽略大小写后可能会有多个词条满足要求，不知道这个问题怎么解决，烦请作者考虑一下这个功能，谢谢！

**Comment by Sapph1reX** [comment]
好的，我考虑一下，谢谢啦

**Comment by sth2018** [comment]
@Sapph1reX 对本地mdx词典已解决大小写敏感问题

**Comment by Sapph1reX** [comment]
好的，请问已经更新了吗？

**Comment by Sapph1reX** [comment]
谢谢作者，请问已经更新了吗？

**Comment by sth2018** [comment]
还没打包更新

**Comment by Sapph1reX** [comment]
测试了一下，但没有效果呀，请问需要在哪里设置吗？

**Comment by sth2018** [comment]
只对本地mdx词典有效

**Comment by Sapph1reX** [comment]
的确是本地导入的

**Comment by sth2018** [comment]
我是这样设置的，没问题
![test](https://user-images.githubusercontent.com/40681172/44138296-0606f36a-a0a6-11e8-8485-c1824d9c4828.png)

**Comment by sth2018** [comment]
字典文件是mdx扩展名吗？

**Comment by Sapph1reX** [comment]
是这样的，我觉得没什么问题呀
![1](https://user-images.githubusercontent.com/38830276/44139187-f0aca692-a0a8-11e8-8dd9-781c8f2b7604.png)
![untitled picture](https://user-images.githubusercontent.com/38830276/44139188-f0ecee00-a0a8-11e8-9600-5f9d557a7bb3.png)

**Comment by sth2018** [comment]
看起来确实没有问题，你确定改一下大小写就能查到内容了？

**Comment by Sapph1reX** [comment]
是的，查stoic时Collins有结果但SOED没有，查Stoic时SOED有结果但Collins没有

**Comment by sth2018** [comment]
麻烦你把有问题的词典上传一下，我看看具体问题出在哪里

**Comment by Sapph1reX** [comment]
[Collins COBUILD (EN - HD).zip](https://github.com/sth2018/FastWordQuery/files/2289768/Collins.COBUILD.EN.-.HD.zip)
另一个词典比较大，这里上传不了，您先看看这个吧

**Comment by sth2018** [comment]
找到原因了，已修复

**Comment by Sapph1reX** [comment]
谢谢作者，麻烦了
