### ISSUE TITLE
無法添加LDOCE6真人發音

### ISSUE THREAD

**Issue by Jason19900812** [sth2018/FastWordQuery#31]
使用word query可以用朗文mdx詞典添加真人發音，但是使用FastWordQuery沒有辦法。其他音標、例句、英義都能正常添加，就只有真人發音不行，美式和英式都不行。看了代碼似乎這部分和word query不同，看不出問題在哪。

**Comment by sth2018** [comment]
能否截图看看你的设置？

**Comment by Jason19900812** [comment]
![1](https://user-images.githubusercontent.com/26020285/44071679-467864b8-9fbd-11e8-802a-c5a5743f43bb.jpg)
![2](https://user-images.githubusercontent.com/26020285/44071680-46a73f7c-9fbd-11e8-98fb-ebfbd0380099.jpg)

**Comment by sth2018** [comment]
能把你的字典文件发我看看吗？
![test2](https://user-images.githubusercontent.com/40681172/44071843-313cf95a-9fbe-11e8-9853-9a917776b2d3.png)

**Comment by Jason19900812** [comment]
請問是截圖還是要上傳整個檔案？
![3](https://user-images.githubusercontent.com/26020285/44072059-4e741552-9fbf-11e8-974e-446afe90871c.jpg)

**Comment by sth2018** [comment]
你好，麻烦你把LDOCE6.mdx文件上传一下。谢谢！

**Comment by Jason19900812** [comment]
我是從這裡下載的
https://pan.baidu.com/s/1RD_lVtRT7Z-Y6ebqR3HKQg 
提取密碼是KcW8

如果您在海外的話，我可以再上傳到google drive

**Comment by sth2018** [comment]
你好，经过比对发现，你这个词典不是原版词典，应该是被修改过的版本。
你试试我这个版本
链接: https://pan.baidu.com/s/1x5Su-XzMWIjAdbB5S03GEw 密码: hj8t

**Comment by sth2018** [comment]
你好，修改了一个版本可以兼容你的词典了，如果有需要你可以更新试试。

**Comment by Jason19900812** [comment]
有測試新的版本了，可以正常添加LDOCE6真人發音，真的非常感謝您！
