### ISSUE TITLE
Query出来显示的结果比MDict上的少一些

### ISSUE THREAD

**Issue by Sapph1reX** [sth2018/FastWordQuery#34]
作者您好~我有一个词典（COCA Frequency 60000）在anki上检索出的结果比在MDict上少一些，如下图，请问这是什么原因啊
![1](https://user-images.githubusercontent.com/38830276/44298230-de0d8680-a311-11e8-881f-a553951b4ccd.png)
![untitled picture](https://user-images.githubusercontent.com/38830276/44298231-de0d8680-a311-11e8-8d51-80f09b45e766.png)

**Comment by Sapph1reX** [comment]
需要的话可以把词典打包发给您

**Comment by sth2018** [comment]
你打包共享至百度网盘吧

**Comment by Sapph1reX** [comment]
https://pan.baidu.com/s/1hFI4bq9qqZH033uOs0ZnLQ

**Comment by sth2018** [comment]
查询结果有什么不一样吗？
![test](https://user-images.githubusercontent.com/40681172/44298559-ec5ea100-a317-11e8-9347-f5cf4ba3d575.png)

**Comment by Sapph1reX** [comment]
那个百分比PC端上可以显示，但iOS上和anki的编辑框里显示不出来

**Comment by sth2018** [comment]
那个百分比是通过css跟js呈现的，这应该是Anki软件pc端跟手机端对js和css的支持不一致引起的吧

**Comment by Sapph1reX** [comment]
应该是，但pdawiki上有人把css和js整合成了那个mdd文件，在iOS上的MDict上百分比就可以正常显示了，不知道能不能用类似的方法让anki里的卡片也能这样（我尝试直接把mdd拷进anki的文件里但没有效果）

**Comment by sth2018** [comment]
css跟js文件是保存在mdd文件中的，mdict需要整合mdd应该是由于这个原因吧（我没使用过IOS版MDict，这是我猜的）。目前FWQ这个插件已经把css跟js同步到Anki的媒体库了的，显示不出来应该是Anki对css和js的支持引起的吧。

**Comment by Sapph1reX** [comment]
还有一个问题：能不能在anki的添加窗口里更改Configuration呀？

**Comment by sth2018** [comment]
Add的时候不是可以操作FastWQ菜单项的Options选项打开配置窗口吗？

**Comment by Sapph1reX** [comment]
是的，但每次都需要切出去设置，感觉稍稍有点麻烦 :( 如果能在Add窗口里用快捷键直接切换就方便多了（不过这个功能也不是特别需要）

**Comment by sth2018** [comment]
好，我看看以什么形式加上会比较方便

**Comment by Sapph1reX** [comment]
嗯嗯，麻烦了

**Comment by sth2018** [comment]
已经在AddCards窗口添加了Options的菜单项了，你可以更新试试看

**Comment by Sapph1reX** [comment]
已更新，谢谢作者啦

**Comment by Sapph1reX** [comment]
我去问了AnkiMobile的开发者，得到了以下回复并找到了Anki Manual里关于js的部分
请问能不能尝试修改一下代码，让AnkiMobile上也能完整地显示词典内容呢？麻烦作者了

**Comment by Sapph1reX** [comment]
以及想给作者打赏～持续更新真的辛苦啦

**Comment by sth2018** [comment]
谢谢你的支持，目前不需要啦！
你说的回复在什么地方？是IOS版的，还是Android？

**Comment by sth2018** [comment]
看了Anki作者的回复和对应的文档说明，Anki是不支持外部js文件的，我换了一种形式加载js代码，已经可以看到后面的百分比条了，但不知道会不会有其他的兼容性问题，还需要多测试些词典才可以。
你手动更新一下（解压到插件目录覆盖原文件就可以了）
for 2.0：[release20.zip](https://github.com/sth2018/FastWordQuery/files/2301407/release20.zip)
for 2.1：[release21.zip](https://github.com/sth2018/FastWordQuery/files/2301410/release21.zip)

**Comment by Sapph1reX** [comment]
已更新，成功显示百分比条，谢谢作者！暂时没有发现什么兼容性问题（用了几分钟后AnKindle那个插件报了个错，但重新安装好像就没问题了）
惟一的变化是Query的速度好像减慢了一些（大概是原来的2/3，但完全可以接受），特别是开始的时候，只比Word Query快一点了hhh
不知道是不是修改了代码的原因

**Comment by sth2018** [comment]
慢的话在Setting里把线程数调大一点

**Comment by Sapph1reX** [comment]
我之前已经调到100了，也有可能是电脑那时候运行速度比较慢吧

**Comment by sth2018** [comment]
与查询速度相关的代码这段时间没有修改过，只有一个忽略大小写会影响性能，没做过详细的性能测试，具体影响有多大我也不确定

**Comment by Sapph1reX** [comment]
好的，那就不考虑这些啦！测试如果稳定的话就麻烦作者更新吧，谢谢 :)

**Comment by Sapph1reX** [comment]
请问作者线程数调太高有没有什么副作用啊

**Comment by Sapph1reX** [comment]
例如会不会导致大量Query时漏掉少数几个词之类的，需要多操作几遍？

**Comment by sth2018** [comment]
对于Web词典太高的话会有查询失败的风险，对于本地词典就影响不大。
你说的会漏掉就可能是量太大，词典网络访问失败的原因引起的。

**Comment by Sapph1reX** [comment]
知道啦，谢谢作者

**Comment by Sapph1reX** [comment]
发现了一个小问题：在Add窗口查询一个已经有的词（单词的field会变成红色）的时候，即使之后不创建卡片也会产生一个重复的空卡片，必须通过Check
Database删掉。这样的话下次同步时PC端会强制覆盖AnkiWeb的文件，有时候会导致学习进度丢失，希望您检查一下是不是插件的原因。

**Comment by sth2018** [comment]
你别用插件查询，手动输入添加重复卡片试试

**Comment by Sapph1reX** [comment]
我试了一下，输入单词之后browser里面已经有的那张卡不会标红，一旦Query之后那张卡就显示有重复了，我觉得是查询的时候自动添加了一张卡

**Comment by sth2018** [comment]
你输入单词后再手动输入其他字段，单词肯定会变红的，这是Anki显示重复卡片的形式

**Comment by sth2018** [comment]
根据你的描述，我想Add窗口可能是存在一个问题，晚点我修复

**Comment by Sapph1reX** [comment]
是的，Add窗口肯定会变红，但如果不创建卡片的话Browser里面那张已经存在的卡片不会变红，而Query之后Browser里的卡立刻就变红了，应该说明加了一张重复的卡吧

**Comment by sth2018** [comment]
嗯，我知道问题出在哪了，等我方便的时候马上修复。谢谢你的提醒！

**Comment by Sapph1reX** [comment]
没事～辛苦啦

**Comment by Sapph1reX** [comment]
作者您好，之前那个问题修复了，但又有一个小问题：输入单词后如果马上Query的话单词会消失并显示field为空，导致每次输入单词后要等一两秒再Query才能正常工作，对效率有一些影响，能不能麻烦您检查一下这个问题？

**Comment by sth2018** [comment]
我测试没有碰到你说的问题，能详细描述一下操作步骤吗？

**Comment by Sapph1reX** [comment]
https://pan.baidu.com/s/1Wq6lyzZZUPoruSLotBT2lQ
视频太大了好像没办法直接上传，只好用百度云了😶

**Comment by sth2018** [comment]
已经找到原因，修复了。
另外你如果要大量添加单词的话，最好的方式是使用导入，新建一个txt文件一个单词一行，然后用Anki的导入功能，再使用FastWQ批量查询，才是最高效的。

**Comment by Sapph1reX** [comment]
谢谢作者～
我一直手动添加是想把看到的原句输入到anki里（这个没办法Query），这样背单词的时候更容易想起来，不过也谢谢您的方法，我以前没有尝试过，以后会考虑。

**Comment by Sapph1reX** [comment]
作者您好，请问可以实现添加卡片后光标自动定位到待查询区域的功能吗？我查询一个词之后会自己加一些笔记，添加卡片后光标就会留在后面的区域里，每次都要手动调节，感觉如果能自动回到上面就好啦

**Comment by sth2018** [comment]
能用图片形式说明一下吗？

**Comment by Sapph1reX** [comment]
比如我先在“单词”里输入要查询的词，查询之后再在“原句”中输入书中的句子，之后添加卡片，光标会像图中那样留在“原句”里，要手动定位到“单词”中才能输入下一个（先添加原句再查询也一样）。如果添加卡片后光标能自动跳到“单词”那个区域，方便直接输入下一个单词，整个过程就会流畅很多

**Comment by sth2018** [comment]
明白你的意思了，但这需要Anki作者修改才能满足你的要求，这不是插件所控制的范围。

**Comment by Sapph1reX** [comment]
好的，那我去问问作者，谢谢啦

**Comment by Sapph1reX** [comment]
最近发现有些日语词典输入假名的时候查询不出来，请问作者能检查一下是什么原因吗？

**Comment by Sapph1reX** [comment]
我发现原因了，不用麻烦您检查了。

**Comment by sth2018** [comment]
如果可以的话把原因说一下，方便其他人在遇到相同问题时参考。

另外，如果有新的问题麻烦创建一个新的标题，一直在同一主题下面，一不方便我查看回复，另一方面也不方便其他使用者遇到相同问题时参考。
谢谢！

**Comment by Sapph1reX** [comment]
嗯嗯 好的
