### ISSUE TITLE
anki安卓端同步到一半闪退

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#36]
今天中午用FWQ查询了一些今天刚添加的卡片，随后就发现了99%卡住不动的bug。

后来用电脑端anki同步到ankiweb没问题，但是用anki安卓端再同步的时候，每次都同步到一半就闪退。有一次同步是科学上网，跳出来错误提示是今天查询的某张卡片的内容。

觉得会不会和那个bug有关，想更新了FWQ后再查询、同步一次。能否麻烦将最新的版本打包一下呢？（我直接从github下载最后一次更新的几个py文件，再替换电脑里的，打开anki后报错。）

还有不知道是不是幻觉，现在FWQ查询起来似乎比以前慢了？是不是和忽略大小写的功能有关。如果可能的话，建议忽略大小写也放到settings里面，做成可选项，就像忽略声调一样。

**Comment by sth2018** [comment]
影响同步应该不会，我一会打包更新一下。
忽略大小写对性能的影响会有，但不会特别大，你本地查询的话可以在Setting里把线程数设置大一点，查询就会快很多。

**Comment by sth2018** [comment]
已经打包发布了一个新的版本，除了修复你之前提交的Bug外，还修复了一些其他的问题，你再试试看还有没有同步问题

**Comment by Steven630** [comment]
還是不行，要崩潰啦。有辦法選中一些卡片，把查過的fields全都刪除嗎？

因為今天在電腦端的操作，僅僅是增加單詞，然後用FWQ查而已。

好像安卓端原本就有bug，如果template太複杂，就會影響同步（2.8.4的版本更新説修復了這個問題，可能修復得不徹底）。

**Comment by sth2018** [comment]
你可以删除重新导入，或者找一个查询结果为空字串的词典，然后在Setting里勾上强制更新。

**Comment by sth2018** [comment]
另外，其实你可以先在电脑上导出备份（可以包含媒体跟学买进度的），然后删除再重新同步，看是否是因为这个课件引起的问题。

**Comment by Steven630** [comment]
謝謝啦，剛才強制上傳collection，再同步了一次才解決的。折騰一天終於有結果了

**Comment by Steven630** [comment]
ios的好贵啊……
