### ISSUE TITLE
Dictionary names and fields translated to English

### ISSUE THREAD

**Issue by patzzz** [sth2018/FastWordQuery#40]
Some dictionary names and fields aren't translated to English (they're only in Chinese), but some fields can be interesting for English learners too (for example: phonetics and pronunciations).

I don't understand these dictionaries and fields and I test them one by one:
![fwq_chinese](https://user-images.githubusercontent.com/25534423/44309315-102bf080-a3c5-11e8-856c-e9633bca0115.png)

Could you translate these texts to English?

Thanks.

**Comment by sth2018** [comment]
These dictionaries are English-Chinese, I think it's suitable for English learner who is Chinese language native, so I didn't translate it.
If you want to rewrite by self, you can write like this
for class: @register([u'Chinese_dictionary_name', u'English_dictionary_name'])
for fields: @export([u'Chinese_field_name', u'English_field_name'])

I'll translate these fields. Thank you for your suggestion.

**Comment by Clement-Jean** [comment]
Can I help translating ?

**Comment by sth2018** [comment]
@Clement-Jean 当然可以，非常感谢

**Comment by Clement-Jean** [comment]
I did the translation, if you need any help for translation or coding features please contact me 🙏

**Comment by sth2018** [comment]
@Clement-Jean, Thanks. By the way, can u translate dictionaries that adapt to Anki 2.1 too?

**Comment by Clement-Jean** [comment]
oh yes sure

**Comment by sth2018** [comment]
Pls using defined symbol in lang.py first when u translate.
Example: 
'''python
@export(u'音标')
'''
change to
'''python
@export('PHON')
'''
Thank you.

**Comment by Clement-Jean** [comment]
oh, i just saw the lang.py exports, I will change on the next version.
