### ISSUE TITLE
**MDX-Ldoce6 not working**

### ISSUE THREAD

**Issue by tuannguyen110** [sth2018/FastWordQuery#42]
MDX-Ldoce6 not working in my cases. 
I already download the ldoce6.mdx and ldoce6.mdd. Then I selected the dictionary folder. But MDX-Ldcoe6 not display when I choose "Dictionary".
Can you help me to fix it. Thank you!
![image](https://user-images.githubusercontent.com/42630007/44502489-e4a65000-a6bb-11e8-9182-f67d7a3d0867.png)

**Comment by sth2018** [comment]
look #33

**Comment by tuannguyen110** [comment]
Thank you, sir!
