### ISSUE TITLE
Non of the https services seem to work on macOS

### ISSUE THREAD

**Issue by sandersantema** [sth2018/FastWordQuery#44]
**Describe the bug**
There is no error, but when for instance using cambridge definition no field is updated. Other things like the non https sources and bing images do work however. 

**To Reproduce**
1. Query for word using macOS and a https source. 
2. Non of the fields get filled in. 

**Expected behavior**
A return from the query. 

**Desktop (please complete the following information):**
 - OS: macOS
 - Version Anki: 2.1.2 FastWordQuery: 2.1.8

**Comment by sth2018** [comment]
I'm trying to fix it. thx!

**Comment by sth2018** [comment]
Download the newest sources & try it again pls. thx!

**Comment by sandersantema** [comment]
Unfortunately this still doesn't work :(

**Comment by sandersantema** [comment]
No error either, at least not that I can see.

**Comment by sandersantema** [comment]
Is this what you changed in the last update?

**Comment by sandersantema** [comment]
Woops accidentally closed the issue.

**Comment by sth2018** [comment]
Take some screenshots for me pls.

**Comment by sth2018** [comment]
Maybe it's because the Oxford online dictionary access denied, u can try the Oxford Learning or other dictionaries.

**Comment by sandersantema** [comment]
Non of the completions sources which use https work. So the Oxford Learning dictionary won't work either. 

I believe the problem has to do with the openurl part of python and the certifi package or possibly openssl or the proprietary variant which Apple has preinstalled on macOS (Apple's ssl version causes a lot of problems).

**Comment by sth2018** [comment]
I found the error about https online dictionaries & fixed it. 
You can try it again. Thx!

**Comment by sandersantema** [comment]
Thank you very much, it works now. Although oxford/ oxford learner still don't work, they do say there is a changed field but the field stays empty. Cambridge does work.

**Comment by sth2018** [comment]
If it shows you a changed field but the field still empty. Because the dictionary query result was empty.
