### ISSUE TITLE
Config delete button not visible on macOS

### ISSUE THREAD

**Issue by sandersantema** [sth2018/FastWordQuery#47]
**Describe the bug**
The button to delete a config in the options window isn't visible on macOS. All though it does still work when you click in the area. 

**To Reproduce**
1. Go to options window

**Expected behavior**
A button should be visible.

**Screenshots**
<img width="731" alt="schermafbeelding 2018-08-27 om 17 21 08" src="https://user-images.githubusercontent.com/21057514/44668495-d8a0f200-aa1d-11e8-9f08-e5aa7532db27.png">

**Comment by sth2018** [comment]
Yes, I knew about this problem. 
It's worked fine on Windows, but I didn't know why it's don't work on macOS. 
I'll continue to work on fixing it.
