### ISSUE TITLE
朗文英韩词典

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#49]
https://www.ldoceonline.com/dictionary/english-korean/word

如果方便的话，可否增加这个词典呢？谢谢。

另外反映一个问题，百度汉语详细解释在anki安卓端显示不会自动换行（适应屏幕），而是会全屏显示（手机小屏幕显示整个网页，字很小）。

再次感谢。

**Comment by sth2018** [comment]
朗文英韩词典，查询到的发音是美音，所以只有解释
[longman_ko.zip](https://github.com/sth2018/FastWordQuery/files/2343255/longman_ko.zip)

百度汉语改对应的CSS样式应该可以达到你想要的效果

**Comment by Steven630** [comment]
谢谢！
