### ISSUE TITLE
无法调出MDX-LDOCE6

### ISSUE THREAD

**Issue by catnfish** [sth2018/FastWordQuery#51]
首先对作者表示感谢
折腾了两天后，还是找不到加载本地朗文读音的方法，只好来求助
已经详细阅读https://github.com/sth2018/FastWordQuery/blob/master/docs/get_mdx_ldoce6_sounds.md和https://github.com/sth2018/FastWordQuery/issues/33
试了几种LDOCE6，那个MDX-LDOCE6就是不出来
词典目录设置了，路径也按照issues33设置了
![l1](https://user-images.githubusercontent.com/43199320/45409341-798be000-b6a1-11e8-8ab5-76b47b2a8189.png)
![l2](https://user-images.githubusercontent.com/43199320/45409657-64fc1780-b6a2-11e8-9934-9bbf85965a89.png)
但是字典字段那里就是出不来MDX-LDOCE6，字典字段也只有默认
![l3](https://user-images.githubusercontent.com/43199320/45409667-69c0cb80-b6a2-11e8-907d-f39efa09f85d.png)
词典已经下载了好几遍不同版本分享的，完整翻了一遍issue后发现作者提供分享的过期了
无法进一步确认问题（感觉不像是词典的问题），请指教谢谢

**Comment by sth2018** [comment]
![1](https://user-images.githubusercontent.com/40681172/45413042-c58f5280-b6aa-11e8-95f3-7acfba2e5359.png)
![2](https://user-images.githubusercontent.com/40681172/45413051-cde78d80-b6aa-11e8-9b3c-b0b48a929e26.png)
这两个地方对吗？

**Comment by catnfish** [comment]
> ![1](https://user-images.githubusercontent.com/40681172/45413042-c58f5280-b6aa-11e8-95f3-7acfba2e5359.png)
> ![2](https://user-images.githubusercontent.com/40681172/45413051-cde78d80-b6aa-11e8-9b3c-b0b48a929e26.png)
> 这两个地方对吗？

第一个图对应的是一楼我发的最后一张图？请问要核对哪里？MDX-LDOCE6这个没有出来（也正是问题所在），要不分享一下您用的模板和词典我重新再来一遍？

第二张图对应的是一楼的第二张图的右侧，MDX-LDOCE6没有出现相应打勾项，有一个叫“本地词典－LDOCE6”的已经打上了勾，按33里的解释也更改了辞典目录见图的左侧

谢谢

**Comment by sth2018** [comment]
不好意思，手机上看得不是太仔细，如果是这种情况的话，有可能是字典问题。
你试试下载我的字典文件看可不可以吧
链接：https://pan.baidu.com/s/1nBFgnsU61YMgCY1ReV60ZQ 密码：glnm

**Comment by catnfish** [comment]
大写的感谢！终于有菜单项出来了，谢谢！
正在研究如何替换已有的牌组中的发音
完了把几个下载提取不成功的总结一下方便他人

**Comment by xudy1120** [comment]
一个插件发生了错误。
请把它报告在插件的论坛上:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "C:\Users\adeas\AppData\Roaming\Anki2\addons\fastwq\gui\options.py", line 186, in _after_build
    self.build_tabs_layout()
  File "C:\Users\adeas\AppData\Roaming\Anki2\addons\fastwq\gui\options.py", line 241, in build_tabs_layout
    self.changedTab(maps_list['def'])
  File "C:\Users\adeas\AppData\Roaming\Anki2\addons\fastwq\gui\options.py", line 276, in changedTab
    self.tabs[i].build_layout()
  File "C:\Users\adeas\AppData\Roaming\Anki2\addons\fastwq\gui\options.py", line 379, in build_layout
    if each.get('fld_ord', -1) == ord or each.get('fld_name', '') == name:
AttributeError: 'unicode' object has no attribute 'get'

**Comment by sth2018** [comment]
你更新插件到最新版试试

**Comment by xudy1120** [comment]
已更新解决 感谢

________________________________

**Comment by sstiger1230** [comment]
> 不好意思，手机上看得不是太仔细，如果是这种情况的话，有可能是字典问题。
> 你试试下载我的字典文件看可不可以吧
> 链接：https://pan.baidu.com/s/1nBFgnsU61YMgCY1ReV60ZQ 密码：glnm

您好， 我用您这个版本成功调出了 MDX-LDOCE6 。

现在有一个小问题：使用FastWordQuery进行查询，出来的内容是纯英文的。
但是好像这个字典是包含中文内容，而且使用欧陆词典就能够正常显示出中文来。

不知道我应该怎样设置，才能在FastWordQuery的查询结果中含有中文内容？

谢谢。

提前祝新年快乐！

**Comment by 99MengXin** [comment]
> 大写的感谢！确实是字典问题，终于有菜单项出来了，谢谢！
> 正在研究如何替换已有的牌组中的发音
> 完了把几个下载提取不成功字典的总结一下方便他人

可能是網路上資源版本眾多，無法匹配。
用作者提供的字典檔成功提取MDX-LDOCE6，謝謝。

**Comment by HandsomeLuoyang** [comment]
> 不好意思，手机上看得不是太仔细，如果是这种情况的话，有可能是字典问题。 你试试下载我的字典文件看可不可以吧 链接：https://pan.baidu.com/s/1nBFgnsU61YMgCY1ReV60ZQ 密码：glnm

过期了，请问可以补上嘛，或者我该去哪里下载呢

**Comment by jier-tech** [comment]
https://www.laohuang.net/20161113/awesometts-mdx-server/
这里好像可以用

**Comment by HandsomeLuoyang** [comment]
> https://www.laohuang.net/20161113/awesometts-mdx-server/ 这里好像可以用

谢谢
