### ISSUE TITLE
Vocabulary MDX

### ISSUE THREAD

**Issue by ajli66** [sth2018/FastWordQuery#52]
親愛的作者 您好～

非常感謝您製作這個add-on，讓我在學習英文上進步很多，
我手上有一個vocabulary.com的mdx檔，
請問我要 如何像朗文字典一樣加入到fast word query裡面？
謝謝！

**Comment by sth2018** [comment]
像下面这样把字典添加到本地词典目录列表里面就可以了，不过只有Default字段
![dict_folder_01](https://user-images.githubusercontent.com/40681172/45585673-dd6d0d80-b91a-11e8-85f6-765e961d6efa.png)
![dict_folder_02](https://user-images.githubusercontent.com/40681172/45585680-f4abfb00-b91a-11e8-95d6-e709036e9197.png)
