### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by colizuo** [sth2018/FastWordQuery#53]
**Describe the bug**
当打开anki时，弹出说
AttributeError: 'module' object has no attribute '_create_unverified_context'
**Desktop (please complete the following information):**
 - OS: linux
 - Version 2.0.52

**Comment by sth2018** [comment]
这是安装了FastWQ插件后出现的异常吗？

**Comment by sth2018** [comment]
找到问题所在了，你试试把FastWQ.py中，这下面这行代码删除或注释
```python
ssl._create_default_https_context = ssl._create_unverified_context
```
