### ISSUE TITLE
日语单词查询无结果

### ISSUE THREAD

**Issue by Sapph1reX** [sth2018/FastWordQuery#59]
作者您好，今天我用日语词典查单词，发现词中如果有浊音（类似ぜ、パ这样的假名）就得不到结果，希望您能修复一下这个问题。谢谢作者！

**Comment by sth2018** [comment]
点击“大辞泉”菜单项无效吗？

**Comment by Sapph1reX** [comment]
有效果，但显示还是在“日汉双解词典”上

**Comment by Sapph1reX** [comment]
啊，重新安装之后好了，之前不知道是什么回事..

**Comment by Sapph1reX** [comment]
前一个问题也解决了，在选项里把Ignore Accents去掉就好。想问一下选项里那个Forced Updates of All Fields有什么用呀

**Comment by sth2018** [comment]
作用就是即便查询结果为空白也更新对应字段

**Comment by Sapph1reX** [comment]
好的，谢谢
