### ISSUE TITLE
能否考虑增加百度汉语？

### ISSUE THREAD

**Issue by Steven630** [sth2018/FastWordQuery#6]
https://hanyu.baidu.com/

比如查询“怀仰”，https://hanyu.baidu.com/s?wd=%E6%80%80%E4%BB%B0&device=pc&from=home

有拼音、基本释义、详细释义。

特别是拼音很有用，稍微生僻点的汉语词语有道就查不到了。能否像有道一样可以单独选取拼音。

麻烦作者考虑。非常感谢！

**Comment by sth2018** [comment]
好的，待我把稳定性修改好之后，会添加大家想要的字典服务的。

**Comment by sth2018** [comment]
希望大家能帮忙测试并提交各类异常问题，谢谢！

**Comment by Steven630** [comment]
非常感謝！
