### ISSUE TITLE
部分mdx词典JS无效

### ISSUE THREAD

**Issue by imkaihao** [sth2018/FastWordQuery#61]
部分词典JS效果在Anki里无效。举个例子，以下牛津高阶第八版的的obnoxious这个单词，我把Anki里的Filed中的查词得到的Html与附带的css、js等文件打包了，见[oald8-obnoxious.zip](https://github.com/sth2018/FastWordQuery/files/2407813/oald8-obnoxious.zip)。

原版mdx词典中通过JS使得默认中文解释隐藏，点击某个英文解释或英文例句会出现这个解释或例句的中文解释。
但是Anki桌面端里JS动态效果无效，具体来说学习时第一个card有效，后面的card中无效。
而AnkiDroid中JS动态效果全部无效。

另外，桌面端Anki2.0中安装[JS Booster](https://ankiweb.net/shared/info/1280253613)的话该词典JS有效。

查询了一些资料，这个问题是不是与每次加载新卡片时webview不会刷新（参考[GitHub链接](https://github.com/dae/anki/pull/92)与[Anki Support链接](https://anki.tenderapp.com/discussions/ankidesktop/15180-jquery-support-in-card-templates)）有关呢？

不太明白这个JS无效的词典与那些JS动态效果有效的词典的区别，以及该问题如何解决？

**Comment by imkaihao** [comment]
发一下牛津高阶第八版的mdx文件方便测试。
链接：https://pan.baidu.com/s/1mHsdzyeFKOr0GOEZDJf_GA 密码：c9wm
（注：这里的CSS文件与上述[oald8-obnoxious.zip](https://github.com/sth2018/FastWordQuery/files/2407813/oald8-obnoxious.zip)中的CSS文件略有不同，oald8-obnoxious.zip中的CSS文件我有些小修改，不过不影响JS动态效果。）

实在是麻烦您了:)

**Comment by sth2018** [comment]
好的，我先看看是什么原因。

**Comment by sth2018** [comment]
这个问题是因为JS引起的，修改后对2.0已经正常了（不需要JS Booster插件），但对于2.1仍然会存在只对第一张card生效，后面的card中仍然无效，应该是Anki不刷新引起的。

**Comment by imkaihao** [comment]
测试了一下，修改后对于对于Anki桌面端的确像您说的一样，2.0正常，2.1仍然只对第一张card有效。
对于移动端，我这边AnkiDroid仍然无效。
请问移动端有什么办法解决这一问题呢？
谢谢您:)

**Comment by sth2018** [comment]
我先装个AnkiDroid试试才知道，或者你有没有什么文档资料？

**Comment by imkaihao** [comment]
之前没搜到AnkiDroid与这个问题有关的信息，我现在再搜索一下

**Comment by imkaihao** [comment]
还是没查到什么有用的资料，解决不了就算了吧。
谢谢您哈:)
