### ISSUE TITLE
Can you add this site ludwig.guru for dictionary and example?

### ISSUE THREAD

**Issue by tuannguyen110** [sth2018/FastWordQuery#65]
**Can you add this site ludwig.guru for dictionary and examples?**
This site uses the real examples in articles, so it can help learner improve their reading skill quickly.
Thank you so much.

**Comment by sth2018** [comment]
Now, I have added the site ludwig.guru to web dictionaries.
It includes Definition Examples Random example and First 2 examples fields.
You can download and test it now.

**Comment by tuannguyen110** [comment]
Thank you so much for your work. but it seems you have not updated on the add-on yet.

**Comment by tuannguyen110** [comment]
Thank you a lot :)
