### ISSUE TITLE
依然无法显示 MDX-LODCE6

### ISSUE THREAD

**Issue by nelson7673** [sth2018/FastWordQuery#73]
您好，
我已试过 #51  和  #33  ，

![2018-10-08 2 54 37](https://user-images.githubusercontent.com/23103640/46595631-e745f300-cb0b-11e8-84cc-651fc05c0afd.png)
![2018-10-08 2 54 54](https://user-images.githubusercontent.com/23103640/46595638-ee6d0100-cb0b-11e8-95a0-6d70836aa299.png)

也用了作者您的字典文件，但依然没有出现 MDX-LDOCE6 ，也重新卸载ＦＷＱ几次，但还是无法显示，希望作者能够帮忙查看还有哪里错误吗？麻煩了，感謝～

**Comment by nelson7673** [comment]
太感谢了！总算可以了～
不好意思，再请问如果我想添加其他字典（不知道您有牛津的词典文件吗？），需要做怎么样的更动吗？

**Comment by sth2018** [comment]
你可以参考readme里面的说明。
在字典文件夹管理里面添加就好了
