### ISSUE TITLE
bing xtk 查询不到例句

### ISSUE THREAD

**Issue by Jhering** [sth2018/FastWordQuery#75]
bing xtk 例句字段添加大规模失败。

3000多个条目的gre词汇，全选择以后，用它批量查询添加，只添加了200多个，大多数单词都添加不了例句。

而且如果不一次选这么多，单个查询的话也查询不到，没有添加。

但使用wordquery是能够正常添加的。

**Comment by Jhering** [comment]
bing xtk 词典，
我人在美国，不存在被墙和延不延迟的问题。
gre词汇在bing上基本上全部都能查到。

**Comment by sth2018** [comment]
bing xtk 大量访问的时候不是特别稳定，你换成Bing，查询到的结果是一样的。

**Comment by Jhering** [comment]
好的，我试试。我这边现在是午夜。我明天试试给您反馈。感谢这么快的回复。这是个神器。

**Comment by sth2018** [comment]
我也是方便自己学英语背单词用的
