### ISSUE TITLE
建议增加被查询词突出显示的功能。

### ISSUE THREAD

**Issue by Jhering** [sth2018/FastWordQuery#76]
以例句为例，很多词典查询出来的例句，被查询的那个单词并没有突出显示，看起来很不方便。

其实这个功能现在已经有了，就是cloze。
我现在都是手动查找替换，把{{c1::
替换成html 加粗和颜色代码

能否直接在设置里面增加这个功能？
比如，查询abandon，
那么例句里面的这个词就被突出显示，可以统一自己设置格式。

**Comment by sth2018** [comment]
好的，等我方便的时候加上
