### ISSUE TITLE
有内置的剑桥英英生成alcoholic单词释义不全。

### ISSUE THREAD

**Issue by dly1973** [sth2018/FastWordQuery#79]
在线查询有两个解释：
B1 containing alcohol
C2 a person who is unable to give up the habit of drinking alcohol very often and in large amounts

生成ANKI卡片上只有B1的解释，如有时间请看下。谢谢。

**Comment by dly1973** [comment]
刚发现象MILK等有两个释义的好象只抓取了第一个，第二个没抓到。

**Comment by YuiTatsumi** [comment]
有同樣的問題
現在 FastWQ 的 Cambridge 的擷取規則就是抓首個詞性，當單字有兩個以上詞性時，例如一樓舉的例子 alcoholic，便只會擷取首個 <kbd>adj.</kbd> 含酒精的，而忽略了第二個 <kbd>n.</kbd> 酗酒者，嗜酒者。

**Comment by sth2018** [comment]
此问题已修复，请更新使用

**Comment by YuiTatsumi** [comment]
不好意思，又來麻煩作者您了
我原先根據這文章 [https://reurl.cc/5qYDy](https://reurl.cc/5qYDy) 去改成能顯示英/中文雙解
剛剛更新後，只抓取第一個，第二個詞性沒抓到的問題修復了（這邊謝謝作者先）
但無法再根據那篇土法煉鋼改成讓 Cambridge 顯示中文了
不知道能不能請作者乾脆于 Cambridge（原本的英英辭典）之外，再另外增加個中英雙解的 Cambridge 辭典。不知道這樣工作量大不大，希望不會太麻煩作者，謝謝。

**Comment by sth2018** [comment]
已经添加了剑桥英汉简和剑桥英汉繁在线词典

**Comment by dly1973** [comment]
非常感谢！！

**Comment by YuiTatsumi** [comment]
非常感謝~
回報個問題，發音好像抓不到，試過美式口音、英式口音都不行 
勞煩作者幫忙看一下，謝謝。

**Comment by sth2018** [comment]
确实存在总是，已修复了

**Comment by YuiTatsumi** [comment]
讚，太謝謝了~ ❤️
