### ISSUE TITLE
How can I extract"EXAMPLES FROM OTHER DICTIONARIES" from FastWordQuery - Longman mdx dictionary (MDX-LDOCE6)? and How can I open link at preview window?

### ISSUE THREAD

**Issue by elektrikci** [sth2018/FastWordQuery#81]
Hi
Firstly, I can just say: FastWordQuery is a awesome and useful add-ones that I have seen, so I wanna say my thankful about it.
let me to describe my request by a example:
when I searched "bond" word at my local host dictionary (LDOCE6 at MDX Server), a window like this appeared:

<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/u6kz_pic1.png" border="0" alt="آپلود عکس" /></a>

that there is a "EXAMPLES" bottom which everyone can click on and see second page:

<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/q7cx_pic2.png" border="0" alt="آپلود عکس" /></a>

actually, I want to add "EXAMPLES FROM OTHER DICTIONARIES" section in second picture (or one of examples in this section) to my fields like "Default", "Definition" and etc. from my MDX-LDOCE6.
How can I do that?

Also, I have another problem:
At "Anki desktop" I inserted "default" Field from MDX-LDOCE6 for "bond" word.  In"preview window" when I was clicking on "EXAMPLE" bottom, this window was appeared:

<a href="http://uupload.ir/" target="_blank"><img src="http://uupload.ir/files/odaq_pic3.png" border="0" alt="آپلود عکس" /></a>

How can I find an app to show this link and at the same time I'm using "MDX Server" to see LDOCE6?
 

with best regard;
      Elektrikci

**Comment by sth2018** [comment]
Using LDOCE6 with MDX-Server, It would be including a Default field only.
If u want more fields, you can open dictionary folder manager dialog of add-ons, and add your folder which included LDOCE6.mdx file into the list. 
After that you can choose Dictionary named MDX-LDOCE6, It's including some fields what's you want.

**Comment by sth2018** [comment]
If U can't see the dictionary named MDX-LDOCE6, you can download mdx file using below link & try it again.
link:  https://pan.baidu.com/s/1nBFgnsU61YMgCY1ReV60ZQ 
code： 
glnm

**Comment by elektrikci** [comment]
Thank you about your quick answer;
Actually, I don't have maintained problems with LDOCE6. I have LDOCE6 from your link ant it is okay.

In default state your MDX-LDOCE6 has blew fields:
	1.	Default
	2.	Phonetic Symbols
	3.	British Pronunciation
	4.	American Pronunciation
	5.	Images
	6.	Examples
	7.	Examples with audios
	8.	Definition
	9.	Random example
	10.	First 2 example
	11.	Random example with audio
	12.	First 2 examples with audio

I just want to add new one and change it to:
	1.	Default
	2.	Phonetic Symbols
	3.	British Pronunciation
	4.	American Pronunciation
	5.	Images
	6.	Examples
	7.	Examples with audios
	8.	Definition
	9.	Random example
	10.	First 2 example
	11.	Random example with audio
	12.	First 2 examples with audio
	13.	**Extra Examples**

I want to extract "Extra Examples" from "EXAMPLES FROM OTHER DICTIONARIES" section that there is in LDOCE6, Please see first picture again (_if there is any problem with seeing of pictures tell me to change their links_):
http://uupload.ir/files/u6kz_pic1.png

So, how can I add this new field in MDX-LDOCE6?

**Comment by sth2018** [comment]
I added a new field in the MDX-LDOCE6 dictionary named Extra Examples, u can update & using it to be sure is it you want.

**Comment by elektrikci** [comment]
WooooooW!
you are awesome!
I update it and checked...
I don't know, how can I say my thanks...
thank you so much.
