### ISSUE TITLE
增加词典建议

### ISSUE THREAD

**Issue by guqinglei123** [sth2018/FastWordQuery#83]
建议增加词典https://www.vocabulary.com/，这个词典解释的单词比较地道。
如查询state可以得到：
![image](https://user-images.githubusercontent.com/25784213/47956120-b8bc1a80-dfda-11e8-9578-52f4cb2599f1.png)

可以将其得到的分为：简要示意（大字部分），详细部分（小字部分）。
更希望作者可以说明一下如何去写这些字典的脚本。

**Comment by sth2018** [comment]
你需要的词典已经添加
我也一直想出一份字典文档来的，但一直都没做:(
等抽空一定出份详细的词典开发说明文档来:)
